version: '3'
services:
  frontendapp:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes: 
      - /etc/localtime:/etc/localtime:ro
    working_dir: /app
    ports: 
      - 3000:3000
    tty: true
    networks:
      - pygesres_net
