version: '3'
services:
  app:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: nodejs-labdev_nodejs
    environment:
      - VITEST_UI_BASE_URL=http://172.18.0.4:5173/__vitest__/
    volumes: 
      - ./:/app
      - /etc/localtime:/etc/localtime:ro
    working_dir: /app
    ports: 
      - 5173:5173
    command: yarn run dev
    tty: true
    networks:
      - labdev_net
    extra_hosts:
      - 'host.docker.internal:host-gateway'
networks:
  labdev_net:
    external: true

