version: '3'
services:
  app:
    image: node:current-alpine3.16
    volumes: 
      - ./:/app
      - /etc/localtime:/etc/localtime:ro
    working_dir: /app
    ports: 
      - 3000:3000
    command: yarn run dev
    tty: true
    networks:
      - pygesres_net
    extra_hosts:
      - 'host.docker.internal:host-gateway'
networks:
    pygesres_net:
        name: pygesres
        external: true
