version: '3'
services:
  frontendapp:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes: 
      - /etc/localtime:/etc/localtime:ro
    working_dir: /app
    ports: 
      - 3000:3000
    tty: true
    networks:
      - pygesres_net
    # extra_hosts:
    #   - 'host.docker.internal:host-gateway'
# networks:
#   pygesres_net:
#     name: pygesres
#     external: true
