version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VITEST_UI_BASE_URL=http://172.18.0.4:51204/__vitest__/
    volumes: 
      - ./:/app
      - /etc/localtime:/etc/localtime:ro
    working_dir: /app
    ports: 
      - 3000:3000
      - 51204:51204
    command: yarn run dev
    tty: true
    networks:
      - pygesres_net
    extra_hosts:
      - 'host.docker.internal:host-gateway'
# networks:
#     pygesres_net:
#         name: pygesres
#         external: true
networks:
  pygesres_net:
    driver: bridge
    name: pygesres 
