export const GLOBAL_TYPES_RECOURSE = {
  RECOURSE_TYPE_LIBRO: 'TYPE_LIBRO',
  RECOURSE_TYPE_VIDEO: 'TYPE_VIDEO'
};

export const GLOBAL_STATUS_RECOURSE = {
  REGISTRADO: 'REGISTRADO',
  POR_EMPEZAR: 'POR EMPEZAR',
  EN_PROCESO: 'EN PROCESO',
  CULMINADO: 'CULMINADO',
  DESFASADO: 'DESFASADO',
  DESCARTADO: 'DESCARTADO'
};
export const GLOBAL_UNIT_MEASURE_PROGRESS = {
  UNIT_HOURS: 'HORAS',
  UNIT_VIDEOS: 'VIDEOS',
  UNIT_PAGES: 'PAGINAS',
  UNIT_CHAPTERS: 'CAPITULOS'
};
