export const GLOBAL_TYPES_RECOURSE = {
  RECOURSE_TYPE_LIBRO: 'TYPE_LIBRO',
  RECOURSE_TYPE_VIDEO: 'TYPE_VIDEO'
};

export const GLOBAL_STATUS_RECOURSE = {
  REGISTRADO: 'REGISTRADO',
  POR_EMPEZAR: 'POR EMPEZAR',
  EN_PROCESO: 'EN PROCESO',
  CULMINADO: 'CULMINADO',
  DESFASADO: 'DESFASADO',
  DESCARTADO: 'DESCARTADO'
};
